run:
  go: "1.20"
  timeout: 10m

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
